version: "3"
services:
  backend:
    container_name: final-graduation-backend
    depends_on:
      - db
    build:
      args:
        user: fialho
        uid: 1000
      dockerfile: ./docker/php/php.Dockerfile
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./final-graduation-project-api:/srv
    environment:
      - APP_ENV=local
    command: >
      bash -c "composer install && php /srv/artisan serve --host=0.0.0.0"
  db:
    container_name: final-graduation-database
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=final-graduation-project
    ports:
      - 5432:5432
  frontend:
    container_name: final-graduation-frontend
    image: node:18
    working_dir: /app
    ports:
      - 8080:8080
    command: >
      bash -c "npm install && npm run serve"
    volumes:
      - ./final-graduation-project-web:/app
  nginx:
    container_name: final-graduation-nginx
    image: nginx:1.13
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
    networks:
      default:
        aliases:
          - front.localhost
          - back.localhost
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
