version: "3"
networks:
  database:
  web:
services:
  backend:
    container_name: final-graduation-backend
    depends_on:
      - db
    build:
      args:
        user: fialho
        uid: 1000
      dockerfile: ./docker/php/php.Dockerfile
      context: .
    ports:
      - 8000:8000
    networks:
      - database
      - web
    volumes:
      - ./final-graduation-project-api:/app
    environment:
      - APP_ENV=local
    command: ["php", "/app/artisan", "serve", "--host=0.0.0.0" ]
  db:
    container_name: final-graduation-database
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=final-graduation-project
    ports:
      - 5432:5432
    networks:
      - database
  frontend:
    container_name: final-graduation-frontend
    image: node:16
    working_dir: /app
    ports:
      - 8080:8080
    networks:
      - web
    command: ["npm", "run", "serve"]
    volumes:
      - ./final-graduation-project-web:/app
  nginx:
    container_name: final-graduation-nginx
    image: nginx:1.13
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
    networks:
      - web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

